# Image de base
FROM ubuntu:18.04

# Installation des logiciels de bases (ici la commande ping)
RUN apt update && apt install -y iputils-ping

# definition de l'entrypoint
ENTRYPOINT ["ping"]

# definition de cmd
CMD ["8.8.8.8"]
